# Generated by Django 3.2.9 on 2021-12-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menuitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('total_amount', models.IntegerField()),
                ('list_of_items', models.TextField(default=None, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.restaurantlist')),
            ],
        ),
    ]
