# Generated by Django 3.2.9 on 2021-12-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
