# Generated by Django 3.2.9 on 2021-12-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='New', max_length=20, null=True),
        ),
    ]
