# Generated by Django 3.2.9 on 2021-12-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
