# Generated by Django 3.2.9 on 2021-12-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rest_id',
        ),
        migrations.DeleteModel(
            name='RestaurantOwner',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='RestaurantList',
        ),
    ]
