# Generated by Django 3.2.9 on 2021-12-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlist',
            name='category',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
